version: "3"
services:
    client:
        image: berkekaan/malice:client
        stdin_open: true
        ports:
            - "19006:19006"
        networks:
            - malice-app
        volumes:
            - ./malice:/opt/malice/app:delegated
            - ./malice/mobile-client/package.json:/opt/malice/app/mobile-client/package.json
            - ./malice/mobile-client/package-lock.json:/opt/malice/app/mobile-client/package-lock.json
            - notused:/opt/malice/app/node_modules
    api:
        image: berkekaan/malice:api
        stdin_open: true
        ports:
            - "5000:5000"
        networks:
            - malice-app
        volumes:
            - ./malice/api:/usr/src/app/api:delegated
            - ./malice/package.json:/usr/src/app/package.json
            - ./malice/package-lock.json:/usr/src/app/package-lock.json
            - notused:/usr/src/app/node_modules
networks:
    malice-app:
        driver: bridge

volumes:
    notused:
        
